name: Compile Typst and Release on Commit
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Typst Document
        uses: typst-community/setup-typst@v5
      - run: typst compile divelog.typ divelog.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-document
          path: divelog.pdf
